/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 *
 * Name: Ryan Greene, Jack Napor, Danny Toback, & Richard Huffman
 * Date: Nov 13, 2015
 * Time: 8:00:51 AM
 *
 * Project: csci205FinalProject
 * Package: Game
 * File: ZombieView
 * Description: The view for the whole game, works with the ZombieModel and ZombieController
 *
 * ****************************************
 */
package Game;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rtg008
 */
public class ZombieView extends javax.swing.JFrame {

    /**
     * Creates new form ZombieView
     */
    public ZombieView() {
        setContentPane(new JLabel(new ImageIcon("images/background.jpg")));
        JLabel logo = new JLabel(new ImageIcon("images/rsz_logo.png"));
        logo.setBounds(10, 10, 300, 144);
        this.getContentPane().add(logo);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Board = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        vitalsLabel = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zombie Survival");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Board.setBackground(java.awt.Color.lightGray);
        Board.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Board.setPreferredSize(new java.awt.Dimension(500, 500));
        Board.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btnStart.setText("Start");
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnExit.setText("Exit");
        btnExit.setName(""); // NOI18N
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        getContentPane().add(vitalsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 210, 140));

        lblRound.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblRound.setForeground(java.awt.Color.white);
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 500, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZombieView().setVisible(true);
            }
        });
    }

    public JPanel getBoard() {
        return Board;
    }

    public JButton getBtnStart() {
        return btnStart;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JLabel getVitals() {
        return vitalsLabel;
    }

    public JLabel getLblRound() {
        return lblRound;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Board;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel vitalsLabel;
    // End of variables declaration//GEN-END:variables
}
